/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemperatureRouteImport } from './routes/temperature'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LightsRouteImport } from './routes/lights'
import { Route as CameraRouteImport } from './routes/camera'
import { Route as IndexRouteImport } from './routes/index'

const TemperatureRoute = TemperatureRouteImport.update({
  id: '/temperature',
  path: '/temperature',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LightsRoute = LightsRouteImport.update({
  id: '/lights',
  path: '/lights',
  getParentRoute: () => rootRouteImport,
} as any)
const CameraRoute = CameraRouteImport.update({
  id: '/camera',
  path: '/camera',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/camera': typeof CameraRoute
  '/lights': typeof LightsRoute
  '/login': typeof LoginRoute
  '/temperature': typeof TemperatureRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/camera': typeof CameraRoute
  '/lights': typeof LightsRoute
  '/login': typeof LoginRoute
  '/temperature': typeof TemperatureRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/camera': typeof CameraRoute
  '/lights': typeof LightsRoute
  '/login': typeof LoginRoute
  '/temperature': typeof TemperatureRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/camera' | '/lights' | '/login' | '/temperature'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/camera' | '/lights' | '/login' | '/temperature'
  id: '__root__' | '/' | '/camera' | '/lights' | '/login' | '/temperature'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CameraRoute: typeof CameraRoute
  LightsRoute: typeof LightsRoute
  LoginRoute: typeof LoginRoute
  TemperatureRoute: typeof TemperatureRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/temperature': {
      id: '/temperature'
      path: '/temperature'
      fullPath: '/temperature'
      preLoaderRoute: typeof TemperatureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lights': {
      id: '/lights'
      path: '/lights'
      fullPath: '/lights'
      preLoaderRoute: typeof LightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camera': {
      id: '/camera'
      path: '/camera'
      fullPath: '/camera'
      preLoaderRoute: typeof CameraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CameraRoute: CameraRoute,
  LightsRoute: LightsRoute,
  LoginRoute: LoginRoute,
  TemperatureRoute: TemperatureRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
